name: docker
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      repository:
        required: true
        type: string
      app-name:
        required: true
        type: string
    secrets:
      docker-hub-access-token:
        required: true

jobs:
  image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker hub authentication
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.docker-hub-access-token }}
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: build and push versioned image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          context: .
          cache-from: ${{ inputs.repository }}/${{ inputs.app-name }}:latest
          tags: |
            ${{ inputs.repository }}/${{ inputs.app-name }}:latest
            ${{ inputs.repository }}/${{ inputs.app-name }}:${{ steps.semver_parser.outputs.major }}
            ${{ inputs.repository }}/${{ inputs.app-name }}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            ${{ inputs.repository }}/${{ inputs.app-name }}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
