name: nomad
on:
  workflow_call:
    inputs:
      job-file:
        required: true
        type: string
      address:
        required: true
        type: string
    secrets:
      token:
        required: true
      variables:
        required: false
  
jobs:
  nomad:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1.4.7
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: install nomad
        uses: lucasmelin/setup-nomad@v0.1.0
        with:
            version: "1.6.0"
      - name: write variables into a file
        run: echo '${{ secrets.variables }}' > ./variables.hcl
      - name: run job
        run: nomad job run -address ${{ inputs.address }} -token ${{ secrets.token }} -var-file ./variables.hcl -var version=${{ steps.semver_parser.outputs.fullversion }} ${{ inputs.job-file }}
