on:
  workflow_call:
    inputs:
      dir:
        description: cargo working directory
        required: false
        default: Cargo.toml
        type: string

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build dependencies
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --manifest-path ${{ inputs.dir }}
      - name: install cargo-audit
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - name: run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path ${{ inputs.dir }}
      - name: audit crate
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ${{ inputs.dir }}
      - name: test crate
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --manifest-path ${{ inputs.dir }}
